name: Publish update to NPM

on: 
  push:
    branches:
      - main

jobs:
  publish-npm:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1

      - uses: actions/setup-node@v2
        with:
          node-version: '14.15'
          registry-url: 'https://registry.npmjs.org'
          
      - run: npm install && npm install -g @angular/cli && ng build --prod ng-github-contributions

      - run: npm publish ./dist/ng-github-contributions --access public
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}

  publish-github:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1

      - uses: actions/setup-node@v2
        with:
          node-version: '14.15'
          registry-url: 'https://npm.pkg.github.com'
          
      - run: npm install && npm install -g @angular/cli && ng build --prod ng-github-contributions

      - run: npm publish ./dist/ng-github-contributions --access public
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
